server:
  port: 9010

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5311/${DB_DATABASE}

jwt:
  expiration-time: 600_000
  secret: qO8zR9Avpm1FLzXzo1kS9OytZ+QjzUpgGzkhEwo6hH4=
